package:
  name: openalea.distributed
  version: "0.1"

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  string: distributed
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
    - pywin32 [win]
  run:
    - python
    - numba
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - openalea.deploy
    - networkx
    - opencv
    - matplotlib
    - vtk
    - pywin32 [win]
    - nose
    - dill

test:
  imports:
    - openalea.distributed

